### PR TITLE
Further dev docker environment improvements

### PR DESCRIPTION
**Pull request by Stephen-ONeil**
Summary:
  - switched to a non-root container user
  - used a docker volumes tricks to avoid all the `/node_modules` ownership headaches
    - the ownership headaches are mostly due to user/group ID (mis)matching between the container and the host OS. [Docker's not planning to provide an API to address this](https://github.com/moby/moby/issues/7198). There's a tool called [fixuid](https://github.com/boxboat/fixuid) which we could use, but it adds bloat to the container and even with the tool it's still a headache to match the IDs
    - the volume mounting trick I put together/dug up is mildly hacky in its own way, but it "just works" without extra junk inside the container or additional command line args passed to `docker-compose`
  - did some file watching and tmux-based process management tricks to implement node module reloading inside the containers, triggered when the host's `package-lock.json` is modified

See the README on this branch for more info.

Updates:
  - fixed entrypoint script not being runnable in images built on windows
  - added codespaces support via create react app (well, react-scripts) built in proxy support

Outstanding issues:
  - Window's docker-desktop seems to not mount the project volumes in a way that allows the watch scripts and hot reloading to function?

### CODE REVIEW

**Comment by samiatoui** [comment]
Got this error.

itsg-api-1                | exec /home/entrypoint.sh: no such file or directory
itsg-api-1 exited with code 1
itsg-ui-1                 | exec /home/entrypoint.sh: no such file or directory
itsg-ui-1 exited with code 1

**Review by samiatoui — CHANGES_REQUESTED** [review]
Errors I got:

itsg-api-1                | exec /home/entrypoint.sh: no such file or directory
itsg-api-1 exited with code 1
itsg-ui-1                 | exec /home/entrypoint.sh: no such file or directory
itsg-ui-1 exited with code 1

**Comment by Stephen-ONeil** [comment]
> Errors I got:
> 
> itsg-api-1 | exec /home/entrypoint.sh: no such file or directory itsg-api-1 exited with code 1 itsg-ui-1 | exec /home/entrypoint.sh: no such file or directory itsg-ui-1 exited with code 1

Hmm, sounds like the images built in the wrong context some how. I'll push something that should prevent that, if it still happens then let me know exactly what docker-compose commands you ran and from what directory :+1:

**Comment by samiatoui** [comment]
> > Errors I got:
> > itsg-api-1 | exec /home/entrypoint.sh: no such file or directory itsg-api-1 exited with code 1 itsg-ui-1 | exec /home/entrypoint.sh: no such file or directory itsg-ui-1 exited with code 1
> 
> Hmm, sounds like the images built in the wrong context some how. I'll push something that should prevent that, if it still happens then let me know exactly what docker-compose commands you ran and from what directory 👍

Still facing the error. I ran docker-compose up from root, it33-filtering/ , as I usually would

**Comment by Stephen-ONeil** [comment]
Docker might be reusing existing volumes. Try `docker-compose down && docker-compose build && docker-compose up` just to explicitly get a clean slate. If there's still an error at that point then we'll probably have to get on a call and debug together when I'm back from training, maybe Thrusday?

**Review by samiatoui — APPROVED** [review]
works as expected

**Pull request merged**
